### ISSUE TITLE
add vignette files to GitHub

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/PacFIN.Utilities#1]
The vignette is great but for making edits it would be useful to have the source files included on GitHub

**Comment by andi-stephens** [comment]
Yes, but I'd like to make sure the vignette is up-to-date with Kelli's
changes before I put the source out.

--A.

**Comment by andi-stephens** [comment]
I've got the vignette written but  I'm missing something about getting it to install with the package.  Alas.

**Comment by taylori** [comment]
Thanks for putting the file up there. This way the vignette can be viewed by looking at https://github.com/nwfsc-assess/PacFIN.Utilities/blob/master/inst/doc/PacFIN.Utilities.Vignette.Rmd which is convenient.
