### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/PacFIN.Utilities#19]
Tasks to complete eventually. Feel free to add more to the list.
- [x] cleanAges
   - [x] move code cleanPacFIN
   - [x] change cleanAges to run cleanPacFIN but tell users that it is [deprecated](https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/Deprecated)
- [ ] cleanPacFIN
   - [ ] #74

**Comment by iantaylor-NOAA** [comment]
[] expand `doSexRatio()` to report what fraction of the samples were unsexed and modified

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, let me know if I should open separate issues for this stuff. I'm happy to help with the changes during a less-busy time.

- [ ] change output of `writeComps()` better match SS version 3.30 input format:
  - [ ] remove `ageErr` column when writing length comps. 
  - [ ] rename `season` to `month` and put it before `fleet`
  - [ ] consider writing `Ntows` to a separate file for use in tables as opposed to SS inputs

**Comment by iantaylor-NOAA** [comment]
- [ ] a variety of improvements being committed to the `ian_suggestions` branch. Feel free to cherry pick, merge, rebase, whatever, but I don't want to mess up other people's work, so will just make commits in this branch for now.
