### ISSUE TITLE
work towards having man pages for all functions?

### ISSUE THREAD

**Issue by taylori** [nwfsc-assess/PacFIN.Utilities#2]
It can be very handy to get man (help) pages by typing something like
?combineCALCOM
Currently about half of the functions have comments at the top which can be converted into man pages using the devtools::document function, which relies on the roxygen2 package but not all of these are complete.
The "Individual Function Descriptions" section of the Vignette could be easily converted into this format (and I'm happy to help do so).

**Comment by andi-stephens** [comment]
Yes, I'm working on getting the rest of the functions documented...  I'm at
a GMT meeting the rest of this week.

--A.
