### ISSUE TITLE
How to save files

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/PacFIN.Utilities#28]
PacFIN data files are distributed as .dmp files, but I don't really know what this means or how they differ from .RData files. Is this a file size thing or is there another reason why you use dmp instead of something else? And, what should we use going forward?

**Comment by John-R-Wallace-NOAA** [comment]
'.dmp' was an Splus extension, it's the same as '.RData', since it's 
created by save().  I have been switching over to .RData for a year or so.

**Comment by kellijohnson-NOAA** [comment]
Thanks John. I will save everything as .RData files.
