### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ciallen** [nwfsc-assess/PacFIN.Utilities#3]
Nnames seems to be just names now.
Would be great to change in the documentation (and examples).
Thanks!

**Comment by andi-stephens** [comment]
Hi Caitlin,

    Thanks for the feedback.  Which function are you referring to?  Did you
reinstall the package to get the latest version?

Cheers,

--Andi

**Comment by kellijohnson** [comment]
I see an Nnames in Stratify, which is correct. I don't see it elsewhere using findstr /s Nnames *.R.
