### ISSUE TITLE
cleanPacFIN

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/PacFIN.Utilities#39]
https://github.com/nwfsc-assess/PacFIN.Utilities/blob/eae799217697406a3af0e95b6b9db80b60afc3ba/R/cleanPacFIN.R#L337

@kellijohnson-NOAA I tried testing out this function using the example data in the package.  When CLEAN = TRUE all record were being removed.  I think I traced it back to this line where I think the check should be: 

ifelse(keep_missing_length, TRUE, **!is.na(Pdata$length)**)

rather than 

ifelse(keep_missing_length, TRUE, is.na(Pdata$length))

I wanted to double check that I am understanding the issue correctly prior to pushing the fix.

**Comment by kellijohnson-NOAA** [comment]
Thanks @chantelwetzel-noaa, your correction is spot on. Push away!

**Comment by kellijohnson-NOAA** [comment]
This is a duplicate of #40 right?

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA  Thank you!  I have pushed the correction to this line.  My internet was glitching this morning, sorry for the accidental duplicate issue.

**Comment by iantaylor-NOAA** [comment]
@chantelwetzel-noaa if we could only just clean away all the data, many modeling problems would go away. 
I accidentally duplicated an issue elsewhere on github this morning as well (I got a "404 Not Found" page), so I'd like to think it's a problem with github, not us.
