### ISSUE TITLE
getExpansion_2 turning years into pounds with single fleet model

### ISSUE THREAD

**Issue by CWetzel** [nwfsc-assess/PacFIN.Utilities#4]
If Convert = TRUE for the getExpansion_2 code on line 138 where the catch weight in tons is converted to pounds is accidently multiplying the year column.  I am working with a single fleet model where all areas and gears are grouped and the data frame for catches has two columns; year and catch.  Currently, the indexing for converting to pounds is specified as 2:length(Catchgears) which with my model setup is 2:1 which results with the year column being multiplied by the pound conversion as well.

**Comment by andi-stephens** [comment]
Thanks for this.  How silly!

On my "TODO" list.

**Comment by CWetzel** [comment]
I just looked at the correct and it is still not quite right.  As example, if you have three fleets (aka Catchgears) with a Catch matrix with the dimensions of 4 x years (year, fleet1, fleet2, fleet3), the conversion loop will only convert the the second and third column because the indexing is done as:

Catch[ , 2:length(Catchgears)] * 2204 which would be Catch[ ,2:3] because Catchgears has a length of 3

What should be done in the code is:

Catch[ , 2:dim(Catch)[2]] * 2204

This correction will work for all fleet structures as long as the Catch matrix has year in the first column.

**Comment by andi-stephens** [comment]
Thanks -- you're right.  Alas, I was in a hurry.

**Comment by John-R-Wallace** [comment]
If year isn't always in the first column, I could show you in the off 
season how to code for that, as long as the year column name is somehow 
identifiable and uniquely labeled (e.g. year, Year, YEAR, Years, ...)


-John

**Comment by andi-stephens** [comment]
Thanks, John -- I do know how to find the year column, but I also think
it's entirely appropriate to demand that it be the first one!


--A.

**Comment by andi-stephens** [comment]
Done!
