### ISSUE TITLE
Improve speed of getExpansion_1

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/PacFIN.Utilities#44]
The getExpansion_1 function runs incredibly slow on large data sets.  For Dover sole which has more than 270,000 length records this function took ~ 4.5 minutes.  Need to evaluate what is causing the time sink and see if this could be sped up.

**Comment by kellijohnson-NOAA** [comment]
Cured with the move towards dplyr in compfixes branch.
