### ISSUE TITLE
RWT_LBS not being converted via cleanColumns function 

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/PacFIN.Utilities#47]
https://github.com/nwfsc-assess/PacFIN.Utilities/blob/562be10030cc252fc8bbf8ce2b9b7833f6a9e191/R/cleanColumns.R#L94

The WEIGHT_OF_LANDING_LBS in the new bds pull is listed to be converted to both lwt_lbs and RWT_LB.  However, in the match function the column name is only converted for the first listing.  I have added a workaround in the dover branch but there is likely a better way to fix this.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa we fixed this right in the comps branch? If yes, can you close this issue. Otherwise, I will search for a solution.
