### ISSUE TITLE
Request for non-default value for growth in getExpansion_1

### ISSUE THREAD

**Issue by CWetzel** [nwfsc-assess/PacFIN.Utilities#5]
To ensure that people do not accidently use the default length weight values in the getExpansion_1 function could those values be turned into NAs or NULL requiring the user to specify them in order to use the function?  I think this would ensure that this is not overlooked by the user.

**Comment by andi-stephens** [comment]
Sounds good to me.  I'll take care of that when I get back from the Council
meeting.

--Andi
