### ISSUE TITLE
Tribal and research catches

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/PacFIN.Utilities#53]
The cleanColumns function when applied to catch pulls filters down to columns typically used to work up catches (state, gear, time).  There area some select columns being removed that people may want to look at: 

REMOVAL_TYPE_CODE: Identifies commercial, personal use, and research removals
FLEET_CODE: Identifies tribal, limited entry, open access, and research removals 
CONDITION_CODE: Identifies live vs. dead landed fish

All the above columns are available in the unfiltered catch pull for users to explode and could be added back to the filter catch data frame if the user wanted to stratify by this type of information.  I am fine with the current approach but thought it may be useful to get user feedback (hence posting this issue) to see if this would cause issues for anyone.

**Comment by brianlangseth-NOAA** [comment]
Having this fields included would be helpful for me (I think that is what you are asking @chantelwetzel-noaa )

**Comment by kellijohnson-NOAA** [comment]
Great, I am happy to include any columns that are helpful, I was just trying to remove the detritus of 100+ columns.
