### ISSUE TITLE
Weight units not updated after cleaning

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [nwfsc-assess/PacFIN.Utilities#56]
I see the unfiltered data has FISH_WEIGHT in grams, and values are as expected (in the 1000s). However after cleaning using cleanPacFIN, FISH_WEIGHT is converted to kgs, but the units in FISH_WEIGHT_UNITS still report "G". Easy to see they are obviously not in grams but still useful to correct as its likely to cause confusion.

**Comment by kellijohnson-NOAA** [comment]
Good point @brianlangseth-NOAA we should probably just move the calculated weight to weight_kg and leave the other columns as is. What do you think about that?

**Comment by brianlangseth-NOAA** [comment]
Probably the most intuitive way, much like lengthcm. I like it.

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA I haven't forgotten about this, just ran into other stuff while trying to clean it up. I will fix it soon though. Please let me know if you have a timeline that you need that is faster than the end of the week?

**Comment by brianlangseth-NOAA** [comment]
Thanks @kellijohnson-NOAA . There is no timeline for me. I ignore the weight units and just treat the weight as KG. Its all clearly in KG anyway.
