### ISSUE TITLE
Create an issue template for a data request

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/PacFIN.Utilities#57]
I would LOVE to create an issue template to facilitate data requests. If others have a good idea on a way forward other than using issues, I am open to ideas. I just get lost in emails. I don't see a reason why there would be issues with having requests be public. I think it would actually help in tractability for future assessors because issues could be queried for what and how data was included in the previous request or year when perhaps a different assessor was in charge of the assessment. Does anyone have experience creating issue templates?

**Comment by iantaylor-NOAA** [comment]
I think that @k-doering-NOAA has looked at issue templates.

**Comment by k-doering-NOAA** [comment]
I've only gone as far as looking at the [github guide for issue templates](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) , but it sounds pretty simple to create a custom issue template. I agree, seems a good idea for the use case described.

**Comment by kellijohnson-NOAA** [comment]
closing with a684e64 which created a markdown template
