### ISSUE TITLE
data request for species Vermilion rockfish off Oregon and Washington

### ISSUE THREAD

**Issue by shcaba** [nwfsc-assess/PacFIN.Utilities#61]
**Species**
Vermilion rockfish.

**Data type needed**
- [X] biological data

**Clearance**
I am doing the assessment, so I should have data clearance.

thank you!

**Comment by kellijohnson-NOAA** [comment]
@shcaba I started this and looked for Vermilion using both `RCK8` and `VRML` as PacFIN species codes, see options [here](https://pacfin.psmfc.org/pacfin_pub/data_rpts_pub/code_lists/sp.txt). There is nothing under the former and only Oregon and California for the latter. Were you expecting Washington to be in the mix?

**Comment by shcaba** [comment]
Thank you Kelli. I did not expect to see anything for WA, so not a surprise. Also not a surprise to hear they are under the nominal category only (I believe E.J. confirmed that should be the case for vermilion).
Getting just the Oregon data would be great for me. THANK YOU!

**Comment by shcaba** [comment]
Thank you!
