### ISSUE TITLE
Research Removals

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/PacFIN.Utilities#62]
https://github.com/nwfsc-assess/PacFIN.Utilities/blob/bf73156dd653ae720f0afc7e96b6947328e281e2/R/PullCatch.PacFIN.R#L74

Just glancing at this line of code it looks like we are removing research catches?  Is that correct?  I would argue that these should be included in any pull we provide.  Even though they are often negligible, we should still be accounting for this source of mortality.  For Dover sole, there is a single year of ~300 mt or research catch for a single year so it was important to include these removals.

**Comment by kellijohnson-NOAA** [comment]
No ... data.woR isn't carried forward to anything; instead, `data` is returned.

**Comment by chantelwetzel-noaa** [comment]
Thank you for the confirmation!  I did not have time this morning to walk through the code to understand this for myself.
