### ISSUE TITLE
Provide a Trip and Sample Table for Data

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/PacFIN.Utilities#65]
While the writeComps function does output the number of tows and samples, users have to cut and paste from the composition data file to get this information for inclusion in the stock assessment.

Adding the functionality to the getComps function to output a saved csv file with tows and the number of fish sampled by sex and year would be useful.  This would be akin to the file provided in the nwfscSurvey package by the getN.fn.  Ultimately, looking forward towards the  simplification and streamline of our data processing packages a single function could be developed to provide this information in a standardized way for all data sources (survey, fishery, recreational).

**Comment by kellijohnson-NOAA** [comment]
Part of #8 so closing
