### ISSUE TITLE
Male only CAL comps

### ISSUE THREAD

**Issue by CWetzel** [nwfsc-assess/PacFIN.Utilities#7]
If male sex comps are being used for SS those values need to be written in the first data section rather than the second (e.g. the section that would hold female comps if gender = 3).  The values in the second section should be zero (although the values don't really matter because SS ignores then).  Currently, the males only option puts the male comps in the secondary position.

**Comment by taylori** [comment]
Chantel and I looked into this and further examination of the User Manual and a couple models indicates that the function is working correctly--males should indeed be put into the second section when gender=2 is used.
